# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: "cipgen/kbot"
  tag: "v1.0.7-3ac385b"
  arch: "amd64"
  os: "linux"
secret:
  name: "kbot"
  tokenName: "TELE_TOKEN"
  tokenKey: "token"
securityContext:
  privileged: true
