# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


replicaCount: 1
image:
  repository: "cipgen"
  tag: "v1.0.7-549e2dd"
  arch: "amd64"
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  tokenKey: "token"
securityContext:
  privileged: true
